---
title: "multi-class_classification"
output: html_documentCancel changes
date: '2023-03-28'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r, echo = TRUE}
train_data = read.table("/Users/ruoooofanj2/Desktop/class/umich/biostat/biostat626/Midterm\ 1/training_data.txt", header = TRUE)
test_data = read.table("/Users/ruoooofanj2/Desktop/class/umich/biostat/biostat626/Midterm\ 1/test_data.txt", header = TRUE)
```

```{r, echo = TRUE}
library(caret)
library(ggplot2)
library(MASS)
library(e1071)
set.seed(1223)
train_data$activity = replace(train_data$activity, train_data$activity >= 7, 7)
train_data = train_data[, -1]
index = sample(1:nrow(train_data), 0.8*nrow(train_data))
train1 = train_data[index, ]
test1 = train_data[-index, ]
```

1.lda
```{r, echo = TRUE}
lda.fit = lda(activity ~., data = train1)
lda.pred = predict(lda.fit, test1)
table(lda.pred$class, test1$activity)
ldaaccm = mean(lda.pred$class == test1$activity)
```
2.SVM
```{r, echo = TRUE}
svm_linear_01 = svm(activity ~., data = train1, kernel = "linear", cost = 0.1, scale = F, type = 'C-classification')
pred_svmlinear_01 = predict(svm_linear_01, test1)
table(test1$activity, pred_svmlinear_01)
svmlinear01_accm = mean(test1$activity == pred_svmlinear_01)
```

```{r, echo = TRUE}
svm_linear_05 = svm(train1$activity ~., data = train1, kernel = "linear", cost = 0.5, scale = F, type = 'C-classification')
pred_svmlinear_05 = predict(svm_linear_05, test1)
table(test1$activity, pred_svmlinear_05)
svmlinear05_accm = mean(test1$activity == pred_svmlinear_05)
```

```{r, echo = TRUE}
svm_linear_1 = svm(activity ~., data = train1, kernel = "linear", cost = 1, scale = F, type = 'C-classification')
pred_svmlinear_1 = predict(svm_linear_1, test1)
table(test1$activity, pred_svmlinear_1)
svmlinear1_accm = mean(test1$activity == pred_svmlinear_1)
```

```{r, echo = TRUE}
svm_linear_10 = svm(activity ~., data = train1, kernel = "linear", cost = 10, scale = F, type = 'C-classification')
pred_svmlinear_10 = predict(svm_linear_10, test1)
table(test1$activity, pred_svmlinear_10)
svmlinear10_accm = mean(test1$activity == pred_svmlinear_10)
```
4.SVM with radial kernel
```{r, echo = TRUE}
svm_radial_01 = svm(activity ~., data = train1, kernel = "radial", cost = 0.1, scale = F, type = 'C-classification')
pred_svmradial_01 = predict(svm_radial_01, test1)
table(test1$activity, pred_svmradial_01)
svmradial01_accm = mean(test1$activity == pred_svmradial_01)
```

```{r, echo = TRUE}
svm_radial_05 = svm(train1$activity ~., data = train1, kernel = "radial", cost = 0.5, scale = F, type = 'C-classification')
pred_svmradial_05 = predict(svm_radial_05, test1)
table(test1$activity, pred_svmradial_05)
svmradial05_accm = mean(test1$activity == pred_svmradial_05)
```

```{r, echo = TRUE}
svm_radial_1 = svm(activity ~., data = train1, kernel = "radial", cost = 1, scale = F, type = 'C-classification')
pred_svmradial_1 = predict(svm_radial_1, test1)
table(test1$activity, pred_svmradial_1)
svmradial1_accm = mean(test1$activity == pred_svmradial_1)
```

```{r, echo = TRUE}
svm_radial_10 = svm(activity ~., data = train1, kernel = "radial", cost = 10, scale = F, type = 'C-classification')
pred_svmradial_10 = predict(svm_radial_10, test1)
table(test1$activity, pred_svmradial_10)
svmradial10_accm = mean(test1$activity == pred_svmradial_10)
```
For test file

```{r, echo = TRUE}
svm_linear_1 = svm(activity ~., data = train_data, kernel = "linear", cost = 1, scale = F, type = 'C-classification')
pred_svmlinear_test = predict(svm_linear_1, test_data)
pred_svmradial_test = predict(svm_radial_1, test_data)
```

3.KNN method
```{r, echo = TRUE}
library("class")
knn_model = knn(train = train1, test = test1, cl = train1$activity, k = 1)
table(test1$activity, knn_model)
knnaccm = mean(test1$activity == knn_model)
```

```{r, echo = TRUE}
knn_test_model = knn(train = train_data, test = test_data, cl = train_data$activity, k = 1)
```

4. naivebayes
```{r, echo = TRUE}
library(naivebayes)
naiveBay_model = naive_bayes(as.factor(activity) ~., data = train1, usekernel = T)
nb_predict = predict(naiveBay_model, test1, type = "class")
nbaccm = mean(test1$activity == nb_predict)
```

5.decision tree
```{r, echo = TRUE}
library(rpart)
decisiontree_model = rpart(activity ~., train1, method = 'class')
dt_predict = predict(decisiontree_model, test1, type = 'class')
dtaccm = mean(dt_predict == test1$activity)
```

```{r, echo = TRUE}
write.table(pred_svmlinear_test,row.names = FALSE, col.names = FALSE, file = "multiclass_1223.txt", quote = FALSE)
```






